server:
  port: 8081

#debug: true
logging:
  file:
    name: myfile.log
  level:
    com:
      zzj:
        recruitment:
          dao: debug

spring:
    # database configuration
    datasource:
      url: jdbc:mysql://localhost:3306/recruitment?serverTimezone=UTC&characterEncoding=utf-8&nullCatalogMeansCurrent=true
      username: root
      password: 123456
    # redis pool config
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
    # timestamp transfer to date format
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 100MB


