spring:
  profiles:
    active: dev
#  security:
#    user:
#      password: 123
#      name: zzj
#      roles: admin

mybatis:
  # type-aliases:scan path
  # type-aliases-package:
  # mapper xml:Implement scan path
  mapper-locations: classpath:mappers/*.xml
  property:
    order: BEFORE

custom:
  EncryptionKey: zzjzzj
  ignores:
    post:
      - "/user/login.do"
      - "/user/register.do"
      - "/user/logout.do"
    #pattern:
    #  - "/test/*"



